#!/bin/bash
ip=${1:-"149.28.57.91"}

# 写入trojan一键脚本
echo "bash <(curl -sL https://raw.githubusercontent.com/daveleung/hijkpw-scripts-mod/main/trojan_mod1.sh)" > trojan.sh
chmod +x trojan.sh

cat > dynamic_port.sh <<'EOF'
# 动态端口映射
port=$1

# 删除之前的PREROUTING规则
rules=$(sudo iptables -t nat -L PREROUTING --line-numbers -n -v)
# 按行遍历规则内容
while IFS= read -r line; do
    # 检查该行规则是否涉及目标端口在10000 - 30000范围（针对TCP协议，可按需增加UDP等其他协议判断）
    if echo "$line" | grep -q "tcp" && echo "$line" | grep -q "dpts:10000:30000"; then
        rule_number=$(echo "$line" | awk '{print $1}')
        # 根据规则行号删除对应的规则
        sudo iptables -t nat -D PREROUTING $rule_number
    fi
done <<< "$rules"

# 更新动态端口
iptables -t nat -A PREROUTING -p tcp --dport 10000:30000 -j REDIRECT --to-ports $port
EOF

cat > setup.sh <<EOF
#!/bin/sh
script_path=\$0
current_dir=\$(dirname "\$script_path")
remote_path=root@$ip:/root/nodes/

region=\$(curl -s ipinfo.io | jq -r '.region | gsub(" "; "_")')

# 查询trojan配置并写入nodes.conf文件
CONFIG_FILE=/usr/local/etc/trojan/config.json

domain=\$(grep sni \s\$CONFIG_FILE | cut -d: -f2 | tr -d \",' ')
if [ "\$domain" = "" ]; then
  domain=\$(grep -m1 cert \$CONFIG_FILE | cut -d/ -f5)
fi

port=\$(grep local_port \$CONFIG_FILE | cut -d: -f2 | tr -d \",' ')
line1=\$(grep -n 'password' \$CONFIG_FILE | head -n1 | cut -d: -f1)
line11=\$(expr \$line1 + 1)
password=\$(sed -n "\${line11}p" \$CONFIG_FILE | tr -d \",' ')

echo \$region \$domain \$port \$password > \$current_dir/\$region.nodes.conf

# 绑定端口
bash \$current_dir/dynamic_port.sh \$port

scp \$region.nodes.conf \$remote_path
EOF
chmod +x setup.sh

echo "
# 免密登录服务器
ssh-keygen -t rsa -P ""

ssh-copy-id -i ~/.ssh/id_rsa.pub root@$ip
"
